In [22]:
list(map(lambda name : name.capitalize(), ['atangana','paul','amidou','omar','hasan','hasan']))

['Atangana', 'Paul', 'Amidou', 'Omar', 'Hasan', 'Hasan']

# Import malaria dataset

In [16]:
import pandas as pd
data = pd.read_csv('DatasetAfricaMalaria.csv')

# Explore malaria dataset

In [17]:
data.info()
data.head()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 27 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Country Name                                                                             594 non-null    object
 1   Year                                                                                     594 non-null    int64
 2   Country Code                                                                             594 non-null    object
 3   Incidence of malaria (per 1,000 population at risk)                                      550 non-null    float64
 4   Malaria cases reported                                                                   550 non-null    float64
 5   Use of insecticide-treated bed nets (% of under-5 population)                            132 non-null    float64
 6   Children with fever receiving antimalarial drugs (% of children under age 5 with fever)  122 non-null    float64
 7   Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)    106 non-null    float64
 8   People using safely managed drinking water services (% of population)                    99 non-null     float64
 9   People using safely managed drinking water services, rural (% of rural population)       88 non-null     float64
 10  People using safely managed drinking water services, urban (% of urban population)       176 non-null    float64
 11  People using safely managed sanitation services (% of population)                        132 non-null    float64
 12  People using safely managed sanitation services, rural (% of rural population)           110 non-null    float64
 13  People using safely managed sanitation services, urban  (% of urban population)          132 non-null    float64
 14  Rural population (% of total population)                                                 588 non-null    float64
 15  Rural population growth (annual %)                                                       588 non-null    float64
 16  Urban population (% of total population)                                                 588 non-null    float64
 17  Urban population growth (annual %)                                                       588 non-null    float64
 18  People using at least basic drinking water services (% of population)                    588 non-null    float64
 19  People using at least basic drinking water services, rural (% of rural population)       566 non-null    float64
 20  People using at least basic drinking water services, urban (% of urban population)       566 non-null    float64
 21  People using at least basic sanitation services (% of population)                        588 non-null    float64
 22  People using at least basic sanitation services, rural (% of rural population)           566 non-null    float64
 23  People using at least basic sanitation services, urban  (% of urban population)          566 non-null    float64
 24  latitude                                                                                 594 non-null    float64
 25  longitude                                                                                594 non-null    float64
 26  geometry                                                                                 594 non-null    object
dtypes: float64(23), int64(1), object(3)
memory usage: 125.4+ KB

,Year,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Use of insecticide-treated bed nets (% of under-5 population),Children with fever receiving antimalarial drugs (% of children under age 5 with fever),Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women),People using safely managed drinking water services (% of population),"People using safely managed drinking water services, rural (% of rural population)","People using safely managed drinking water services, urban (% of urban population)",People using safely managed sanitation services (% of population),...,Urban population (% of total population),Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude
count,594.000000,550.000000,5.500000e+02,132.000000,122.000000,106.000000,99.000000,88.000000,176.000000,132.000000,...,588.000000,588.000000,588.000000,566.000000,566.000000,588.000000,566.000000,566.000000,594.000000,594.000000
mean,2012.000000,190.087491,1.068330e+06,42.530303,30.201639,15.013958,33.478990,12.470568,51.549545,28.768939,...,43.164116,3.523061,65.994915,51.449576,84.268498,39.469796,28.077208,48.088375,2.828796,17.342546
std,3.164943,163.054527,2.192802e+06,20.157059,18.903198,12.389166,26.678321,10.078371,24.157416,18.631510,...,18.086118,1.456244,17.283361,18.927868,9.307285,26.304934,24.046725,21.802128,15.678226,20.041257
min,2007.000000,0.000000,0.000000e+00,1.000000,0.500000,0.000000,5.770000,0.930000,11.200000,6.370000,...,9.860000,-4.650000,28.960000,17.050000,52.010000,4.990000,1.890000,12.580000,-30.559482,-24.013197
25%,2009.000000,30.857500,2.211750e+03,26.675000,17.275000,5.763285,8.975000,4.185000,34.125000,16.532500,...,28.795000,2.512500,52.375000,37.075000,78.080000,18.197500,8.842500,30.775000,-6.369028,0.824782
50%,2012.000000,174.775000,1.130260e+05,42.900000,29.300000,11.500000,28.390000,10.675000,51.365000,25.410000,...,41.560000,3.730000,64.470000,50.435000,85.420000,32.555000,18.815000,44.695000,6.744051,18.611308
75%,2015.000000,347.637500,1.154808e+06,56.325000,42.625000,21.850000,43.890000,16.887500,70.747500,35.725000,...,56.945000,4.450000,79.165000,62.245000,90.082500,54.810000,38.082500,58.845000,12.862807,31.465866
max,2017.000000,585.540000,1.682113e+07,95.500000,76.900000,59.600000,92.660000,39.930000,89.540000,78.120000,...,88.980000,7.400000,99.870000,99.830000,99.920000,100.000000,95.180000,98.300000,33.886917,57.552152

# List of country that the name start with "C"

In [15]:
filtering_cond = data['Country Name'].apply(lambda country: country.startswith('C'))
data[filtering_cond]

,Country Name,Year,Country Code,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Use of insecticide-treated bed nets (% of under-5 population),Children with fever receiving antimalarial drugs (% of children under age 5 with fever),Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women),People using safely managed drinking water services (% of population),"People using safely managed drinking water services, rural (% of rural population)",...,Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude,geometry
6,Cabo Verde,2007,CPV,0.15,18.0,NaN,NaN,NaN,NaN,NaN,...,2.66,81.39,71.02,88.48,54.85,38.90,65.77,16.002082,-24.013197,POINT (16.002082 -24.013197)
7,Cameroon,2007,CMR,386.68,0.0,NaN,NaN,NaN,NaN,NaN,...,3.96,60.09,38.85,81.55,39.25,23.01,55.66,7.369722,12.354722,POINT (7.369722 12.354722)
8,Central African Republic,2007,CAF,471.11,0.0,NaN,NaN,NaN,NaN,NaN,...,2.30,51.10,38.18,71.87,20.55,8.76,39.50,6.611111,20.939444,POINT (6.611111 20.939444)
9,Chad,2007,TCD,210.71,48288.0,NaN,NaN,NaN,NaN,NaN,...,3.55,40.34,30.88,74.12,11.15,5.75,30.45,15.454166,18.732207,POINT (15.454166 18.732207)
10,Comoros,2007,COM,60.65,38913.0,NaN,NaN,NaN,NaN,NaN,...,2.41,85.86,84.59,89.14,33.44,28.68,45.76,-11.652000,43.372600,POINT (-11.652 43.3726)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,Chad,2017,TCD,172.30,1962372.0,NaN,NaN,NaN,NaN,NaN,...,3.87,38.70,29.47,69.85,8.34,1.89,30.12,15.454166,18.732207,POINT (15.454166 18.732207)
550,Comoros,2017,COM,3.97,3230.0,NaN,NaN,NaN,NaN,NaN,...,2.85,80.17,76.91,88.22,35.86,32.07,45.24,-11.652000,43.372600,POINT (-11.652 43.3726)
551,"Congo, Dem. Rep.",2017,COD,329.13,16793002.0,NaN,NaN,NaN,NaN,NaN,...,4.57,43.24,22.83,69.35,20.46,18.17,23.38,-4.038333,21.758664,POINT (-4.038333 21.758664)
552,"Congo, Rep.",2017,COG,240.64,127939.0,NaN,NaN,NaN,45.35,19.06,...,3.26,73.22,45.72,87.09,20.17,6.26,27.20,-0.228021,15.827659,POINT (-0.228021 15.827659)
553,Cote d'Ivoire,2017,CIV,362.36,3475953.0,NaN,NaN,NaN,36.55,17.71,...,3.44,72.87,57.83,87.71,32.13,18.02,46.07,7.539989,-5.547080,POINT (7.539989 -5.54708)

# List of country without Malaria case reported

In [32]:
filtering_cond = data['Malaria cases reported'].apply(lambda nbre_malaria_case: nbre_malaria_case==0) 
data[filtering_cond]

,Country Name,Year,Country Code,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Use of insecticide-treated bed nets (% of under-5 population),Children with fever receiving antimalarial drugs (% of children under age 5 with fever),Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women),People using safely managed drinking water services (% of population),"People using safely managed drinking water services, rural (% of rural population)",...,Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude,geometry
2,Benin,2007,BEN,480.24,0.0,NaN,NaN,NaN,NaN,NaN,...,4.09,63.78,54.92,76.24,11.80,4.29,22.36,9.307690,2.315834,POINT (9.307689999999999 2.315834)
7,Cameroon,2007,CMR,386.68,0.0,NaN,NaN,NaN,NaN,NaN,...,3.96,60.09,38.85,81.55,39.25,23.01,55.66,7.369722,12.354722,POINT (7.369722 12.354722)
8,Central African Republic,2007,CAF,471.11,0.0,NaN,NaN,NaN,NaN,NaN,...,2.30,51.10,38.18,71.87,20.55,8.76,39.50,6.611111,20.939444,POINT (6.611111 20.939444)
13,Cote d'Ivoire,2007,CIV,509.98,0.0,NaN,NaN,NaN,34.96,16.64,...,3.11,71.72,56.51,89.53,24.72,10.57,41.28,7.539989,-5.547080,POINT (7.539989 -5.54708)
15,"Egypt, Arab Rep.",2007,EGY,0.00,0.0,NaN,NaN,NaN,NaN,NaN,...,1.76,98.38,97.57,99.46,93.05,90.52,96.40,26.820553,30.802498,POINT (26.820553 30.802498)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,Morocco,2016,MAR,0.00,0.0,NaN,NaN,NaN,70.00,39.93,...,2.23,86.64,70.73,96.65,88.42,78.99,94.36,31.794500,-7.084900,POINT (31.7945 -7.0849)
540,Algeria,2017,DZA,0.00,0.0,NaN,NaN,NaN,NaN,NaN,...,2.87,93.56,88.69,95.44,87.59,82.21,89.67,28.033886,1.659626,POINT (28.033886 1.659626)
555,"Egypt, Arab Rep.",2017,EGY,0.00,0.0,NaN,NaN,NaN,NaN,NaN,...,2.03,99.11,98.82,99.49,94.19,91.13,98.30,26.820553,30.802498,POINT (26.820553 30.802498)
568,Libya,2017,LBY,0.00,0.0,NaN,NaN,NaN,NaN,NaN,...,1.70,98.53,NaN,NaN,100.00,NaN,NaN,26.335100,17.228331,POINT (26.3351 17.228331)
574,Morocco,2017,MAR,0.00,0.0,NaN,NaN,NaN,70.27,39.93,...,2.18,86.78,70.73,96.65,88.50,78.99,94.36,31.794500,-7.084900,POINT (31.7945 -7.0849)